apiVersion: apps/v1
kind: Deployment
  - apiVersion: apps/v1
  name: pgsql-master
  namespace: data
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: pgsql-master
            optional: false
        image: postgres:latest
        imagePullPolicy: Always
        name: pgsql-writer
        ports:
        - containerPort: 5432
          hostIP: 10.2.4.1
          hostPort: 15432
          name: postgres-master
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: vol1
          subPath: pgsql-writer/data
        - mountPath: /etc/postgresql/postgresql.conf
          name: vol1
          subPath: pgsql-writer/postgresql-master.conf
        - mountPath: /etc/postgresql/pg_hba.conf
          name: vol1
          subPath: pgsql-writer/pg_hba.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        nfs:
          path: /volume1/kube
          server: apollon.fr59494-home.local.hanapoulpe.org

